__default__:
    queue: normal
    ncpus: 32
    mem: 32G
    ntasks: 1
    name: PIL.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

split_fastq:
    queue: normal
    ncpus: 4
    mem: 16G
    ntasks: 1
    name: PIL.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

align_rna:
    queue: normal
    ncpus: 32
    mem: 128G
    ntasks: 1
    name: PIL.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

# Command to run everything

# First it's necessary to build conda env as the cluster nodes are not connected
# to the network.
# snakemake --conda-create-envs-only --use-conda -j 1

# Build the log directory.
# mkdir -p logs/cluster/

# Run everything on cluster.
# snakemake --cluster "sbatch --mem {cluster.mem} -c {cluster.ncpus} -n {cluster.ntasks} -J {cluster.name} -o {cluster.output} -e {cluster.error}" --cluster-config config/cluster_slurm.yaml -j 32 --use-conda
