__default__:
    queue: fast
    ncpus: 1
    mem: 16G
    ntasks: 1
    partition : common,dedicated
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

split_fastq:
    queue: fast
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

split_fastq_se:
    queue: fast
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

align_rna:
    queue: fast
    partition: common,dedicated
    ncpus: 32
    mem: 32G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

align_SE_rna:
    queue: fast
    partition: common,dedicated
    ncpus: 32
    mem: 32G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

bt2_index:
    queue: fast 
    partition: common,dedicated
    ncpus: 32
    mem: 32G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

split_align_hic:
    queue: fast 
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

merge_split_hic_alignments:
    queue: fast 
    partition: common,dedicated
    ncpus: 32
    mem: 32G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

hic_coverage:
    queue: fast
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

generate_pairs:
    queue: normal 
    partition: common
    ncpus: 1
    mem: 32G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

merge_rebin_cool:
    queue: fast 
    partition: common,dedicated
    ncpus: 1
    mem: 32G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

zoomify_normalize_cool:
    queue: fast 
    partition: common,dedicated
    ncpus: 8
    mem: 32G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

merge_split_rna_alignments:
    queue: fast 
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

rna_coverage:
    queue: fast
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

merge_rna_bam:
    queue: fast 
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

rna_coverage_merge:
    queue: fast 
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

align_chip:
    queue: fast 
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

merge_split_chip_alignments:
    queue: fast 
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

chip_coverage:
    queue: fast 
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

generate_gc:
    queue: fast
    partition: common,dedicated
    ncpus: 8
    mem: 16G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

rifampicine_fw:
    queue: fast
    partition: common,dedicated
    ncpus: 25
    mem: 64G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

rifampicine_rv:
    queue: fast
    partition: common,dedicated
    ncpus: 25
    mem: 64G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err
    
plot_matrix_topA:
    queue: fast
    partition: common,dedicated
    ncpus: 25
    mem: 64G
    ntasks: 1
    name: T7.{rule}.{wildcards}
    output: logs/cluster/{rule}.{wildcards}.out
    error: logs/cluster/{rule}.{wildcards}.err

# Command to run everything

# First it's necessary to build conda env as the cluster nodes are not connected
# to the network.
# snakemake --conda-create-envs-only --use-conda -j 1

# Build the log directory.
# mkdir -p logs/cluster/

# Run everything on cluster.
# snakemake --cluster "sbatch --mem {cluster.mem} -p {cluster.partition} --qos {cluster.queue} -c {cluster.ncpus} -n {cluster.ntasks} -J {cluster.name} -o {cluster.output} -e {cluster.error}" --cluster-config config/cluster_slurm.yaml -j 64 --use-conda
